"""Imported printer catalog (Zebra + TSC + SATO + Honeywell + Citizen + Postek).
Slugs are deduped against the original SEED_PRODUCTS — duplicates are silently skipped.

Prices default to None + price_on_request=True so they show 'Price on request' on the
storefront. Admin can set actual INR amounts via the /admin/products UI any time.
"""

# Brand → form-factor groupings imported from competitor catalog (model names + specs)
IMPORTED_PRINTERS = [
    # ── Desktop ──
    {"slug": "zebra-zd220", "category": "printer", "name": "Zebra ZD220", "brand": "Zebra",
     "form": "Desktop", "dpi": 203, "width": "4-inch",
     "tags": ["Entry-level", "Desktop", "Direct Thermal", "Thermal Transfer"],
     "short_desc": "Entry-level 4-inch desktop barcode printer for low-volume retail and basic shipping.",
     "long_desc": "The ZD220 is Zebra's entry-level desktop printer — proven Zebra reliability at a budget price. Perfect for small retailers, clinics and offices replacing legacy desktop models.",
     "specs": ["203 dpi resolution", "4 IPS max print speed", "USB interface",
               "Print length 991 mm (39\") × 6.4 mm (0.25\")",
               "Print width 104 mm (4.09\") × 25.4 mm (1\")",
               "Ribbon: 74 m ink-out, 0.5\" core"],
     "use_cases": ["Small retail POS", "Clinic & office labels", "Light shipping"],
     "image_index": 0},
    {"slug": "tsc-ta220", "category": "printer", "name": "TSC TA220", "brand": "TSC",
     "form": "Desktop", "dpi": 203, "width": "4.25-inch",
     "tags": ["Desktop", "USB+LAN+RS232", "Workgroup"],
     "short_desc": "Workgroup-class 4.25-inch desktop with full connectivity (USB / LAN / RS232 / USB host).",
     "long_desc": "The TSC TA220 is built for workgroups that need a printer at every workstation — easy to deploy across networks, with full connectivity and 1000-inch print length capacity.",
     "specs": ["203 dpi", "6 IPS max print speed", "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\")",
               "Print width 108 mm (4.25\") × 20 mm (0.8\")",
               "TSPL-EZ + EPL2 + ZPL emulations"],
     "use_cases": ["Office workgroups", "Retail back-office", "Light warehousing"],
     "image_index": 1},
    {"slug": "tsc-te210-te310", "category": "printer", "name": "TSC TE210 / TE310", "brand": "TSC",
     "form": "Desktop", "dpi": 203, "width": "4.25-inch",
     "tags": ["Desktop", "203/300 dpi", "USB+LAN+RS232"],
     "short_desc": "Dual-resolution desktop family — TE210 (203 dpi) for general use, TE310 (300 dpi) for fine detail.",
     "long_desc": "The TE210 / TE310 family lets you choose resolution while keeping the same chassis and footprint — TE210 for shipping/inventory, TE310 for jewelry, electronics and small-format barcodes.",
     "specs": ["203 dpi (TE210) / 300 dpi (TE310)", "6 IPS / 5 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\") at 203 dpi",
               "Print width 108 mm (4.25\")",
               "Ribbon: 74 m / 300 m ink-out"],
     "use_cases": ["Inventory & shipping", "Jewelry & small-format tags", "Electronics labels"],
     "image_index": 2},
    {"slug": "tsc-ttp-345", "category": "printer", "name": "TSC TTP-345", "brand": "TSC",
     "form": "Desktop", "dpi": 300, "width": "4.17-inch",
     "tags": ["Desktop", "300 dpi", "Detail labels"],
     "short_desc": "300 dpi desktop printer for fine-detail labels — jewelry, electronics, lab samples.",
     "long_desc": "The TTP-345 is a focused 300 dpi printer for crisp small-format labels and dense barcodes. The 300 m ribbon capacity reduces media changes during runs.",
     "specs": ["300 dpi", "5 IPS max print speed", "USB + RS232 + USB Host",
               "Print length up to 1016 mm (40\")",
               "Print width 106 mm (4.17\") × 20 mm (0.75\")",
               "Ribbon: 300 m ink-out, 1\" core"],
     "use_cases": ["Jewelry tagging", "Electronics labels", "Lab samples"],
     "image_index": 3},
    {"slug": "tsc-da310", "category": "printer", "name": "TSC DA310 (Direct Thermal)", "brand": "TSC",
     "form": "Desktop", "dpi": 300, "width": "4.16-inch",
     "tags": ["Desktop", "Direct Thermal", "300 dpi", "No Ribbon"],
     "short_desc": "300 dpi direct-thermal desktop — no ribbon, ideal for shipping & POS.",
     "long_desc": "Direct thermal printing means no ribbon costs — perfect for short-life shipping, POS receipts and parcel locker labels at high resolution.",
     "specs": ["300 dpi", "4 IPS max print speed", "USB interface",
               "Print length up to 1016 mm (40\")",
               "Print width 105.7 mm (4.16\")",
               "No ribbon required"],
     "use_cases": ["Shipping labels", "POS receipts", "Parcel lockers"],
     "image_index": 4},
    {"slug": "citizen-cle221-cle331", "category": "printer", "name": "Citizen CL-E221 / CL-E331", "brand": "Citizen",
     "form": "Desktop", "dpi": 203, "width": "4-inch",
     "tags": ["Desktop", "Citizen", "203/300 dpi", "Compact"],
     "short_desc": "Compact Citizen desktop printer — choose 203 or 300 dpi, USB / LAN / RS232.",
     "long_desc": "Citizen's CL-E221 (203 dpi) and CL-E331 (300 dpi) bring Japanese build quality to the desktop — quiet operation, easy media loading, and 8 IPS at 203 dpi.",
     "specs": ["203 dpi / 300 dpi", "8 IPS / 6 IPS", "USB + LAN + RS232",
               "Print length 2540 mm (100\") at 203 dpi",
               "Print width 104 mm (4\")",
               "Ribbon: 300 m ink-out, 1\" core"],
     "use_cases": ["Office labels", "Retail counter", "Healthcare desktops"],
     "image_index": 5},
    {"slug": "zebra-zd421", "category": "printer", "name": "Zebra ZD421", "brand": "Zebra",
     "form": "Desktop", "dpi": 203, "width": "4-inch",
     "tags": ["Desktop", "203/300 dpi", "Wi-Fi", "Bluetooth", "Modular"],
     "short_desc": "Modular desktop with field-installable connectivity (Wi-Fi, BT, Ethernet, Serial).",
     "long_desc": "The ZD421 is the modular sibling of the ZD621 — start with USB and add Wi-Fi, Bluetooth or Ethernet later as your needs evolve. Future-proof your investment.",
     "specs": ["203 / 300 dpi", "6 IPS / 4 IPS",
               "USB + USB Host standard; field-installable Wi-Fi 5 + BT 4.1 + Ethernet + Serial",
               "Print length up to 991 mm (39\")",
               "Print width 104 / 108 mm",
               "Link-OS + ZPL + EPL"],
     "use_cases": ["Growing retail chains", "Healthcare", "Workgroup deployments"],
     "image_index": 0},
    {"slug": "tsc-tx210-tx310-tx610", "category": "printer", "name": "TSC TX210 / TX310 / TX610", "brand": "TSC",
     "form": "Desktop", "dpi": 203, "width": "4.25-inch",
     "tags": ["Desktop", "203/300/600 dpi", "Premium Desktop"],
     "short_desc": "Premium desktop family — TX210/310/610 cover 203, 300 and 600 dpi for any label.",
     "long_desc": "The TX series gives you a single chassis with three resolution choices — TX210 for general use, TX310 for fine detail, TX610 for jewelry/electronics ultra-fine print.",
     "specs": ["203 / 300 / 600 dpi", "8 / 6 / 4 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\") at 203 dpi",
               "Print width 108 mm (4.25\")"],
     "use_cases": ["Multi-application sites", "Jewelry & ultra-fine labels", "Workgroup"],
     "image_index": 1, "featured": True},
    {"slug": "tsc-t800-rfid", "category": "printer", "name": "TSC T800 (RFID)", "brand": "TSC",
     "form": "Desktop", "dpi": 203, "width": "4.4-inch",
     "tags": ["Desktop", "RFID Encoding", "203/300 dpi"],
     "short_desc": "RFID-enabled desktop printer — encode and verify UHF inlays as you print.",
     "long_desc": "The TSC T800 brings RFID encoding to the desktop. Print and encode passive UHF tags in one pass — perfect for retail item-level RFID, asset tagging and pharmacy SKU encoding.",
     "specs": ["203 / 300 dpi", "8 IPS / 6 IPS",
               "USB + LAN + RS232", "RFID UHF encoding (EPC Gen2)",
               "Print length 1270 mm (50\")",
               "Print width 112 mm (4.4\")"],
     "use_cases": ["Retail item-level RFID", "Asset tagging", "Pharmacy"],
     "image_index": 2, "featured": True},
    {"slug": "citizen-cls621-cls631", "category": "printer", "name": "Citizen CL-S621 / CL-S631", "brand": "Citizen",
     "form": "Desktop", "dpi": 203, "width": "4-inch",
     "tags": ["Desktop", "Citizen", "203/300 dpi"],
     "short_desc": "Citizen S-series desktop — quiet, reliable, 360 m ribbon capacity for long runs.",
     "long_desc": "The CL-S621 / CL-S631 deliver Citizen's signature reliability with extended 360 m ribbon capacity — fewer media changes for unattended runs.",
     "specs": ["203 / 300 dpi", "4 IPS", "USB + RS232",
               "Print length 1625.6 mm (64\")",
               "Print width 104 mm (4\")",
               "Ribbon: 360 m ink-out, 1\" core"],
     "use_cases": ["Quiet office environments", "Healthcare", "Retail back-office"],
     "image_index": 3},
    {"slug": "citizen-cls6621", "category": "printer", "name": "Citizen CL-S6621", "brand": "Citizen",
     "form": "Desktop", "dpi": 203, "width": "6-inch",
     "tags": ["Desktop", "Citizen", "6-inch wide"],
     "short_desc": "Wide-format 6-inch desktop printer — for shipping, drum labels and large carton tags.",
     "long_desc": "When 4-inch isn't wide enough, the CL-S6621 prints up to 168 mm (7\") wide — ideal for large shipping labels, drum labels and hazmat compliance tags.",
     "specs": ["203 dpi", "6 IPS", "USB + RS232",
               "Print length 812.8 mm (32\")",
               "Print width 168 mm (7\") × 50 mm (2\")",
               "Ribbon: 360 m"],
     "use_cases": ["Wide shipping labels", "Drum & barrel labels", "Hazmat compliance"],
     "image_index": 4},
    {"slug": "zebra-zd510-hc", "category": "printer", "name": "Zebra ZD510-HC (Healthcare)", "brand": "Zebra",
     "form": "Desktop", "dpi": 300, "width": "1.1875-inch",
     "tags": ["Healthcare", "Wristbands", "300 dpi"],
     "short_desc": "Purpose-built wristband printer for hospitals — Z-Band cartridges, antimicrobial housing.",
     "long_desc": "The ZD510-HC is engineered exclusively for patient-identification wristbands. Snap-in Z-Band cartridges eliminate ribbon hassle, antimicrobial plastics survive daily disinfection, and 300 dpi means barcodes scan first time, every time.",
     "specs": ["300 dpi", "2 IPS (Healthcare) / 4 IPS (Z-Band Fun)",
               "Print width up to 30.16 mm (1.1875\")",
               "Print length up to 558 mm (22\")",
               "Z-Band cartridge media", "Antimicrobial housing"],
     "use_cases": ["Hospital wristbands", "Outpatient ID", "Visitor badges"],
     "image_index": 5},

    # ── Mid-Range Industrial ──
    {"slug": "zebra-zt211", "category": "printer", "name": "Zebra ZT211", "brand": "Zebra",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Mid-range Industrial", "203/300 dpi", "Workhorse"],
     "short_desc": "Mid-range industrial workhorse — proven Zebra build for 24×5 manufacturing & distribution.",
     "long_desc": "The ZT211 brings industrial reliability to mid-volume sites — print 157\" labels, 10 IPS speed, all-metal frame and printhead-life monitoring built in.",
     "specs": ["203 / 300 dpi", "10 IPS / 6 IPS",
               "USB 2.0 + RS-232 + 10/100 Ethernet + USB Host",
               "Print length up to 3988 mm (157\") at 203 dpi",
               "Print width 104 mm (4.09\")", "Ribbon: 450 m"],
     "use_cases": ["Mid-volume warehouses", "Manufacturing", "3PL logistics"],
     "image_index": 0, "featured": True},
    {"slug": "zebra-zt111", "category": "printer", "name": "Zebra ZT111", "brand": "Zebra",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Mid-range Industrial", "Value Industrial"],
     "short_desc": "Value industrial entry — Zebra build quality at a mid-range price point.",
     "long_desc": "The ZT111 is Zebra's most affordable industrial printer. When you need true industrial reliability but the volume doesn't justify a flagship, the ZT111 hits the sweet spot.",
     "specs": ["203 dpi (300 dpi optional)", "10 IPS at 203 dpi, 6 IPS at 300 dpi",
               "USB 2.0 + RS-232 + 10/100 Ethernet + USB Host",
               "Print width 104 mm (4.09\")"],
     "use_cases": ["Mid-volume manufacturing", "Distribution centres", "Workgroup industrial"],
     "image_index": 1},
    {"slug": "zebra-zt231", "category": "printer", "name": "Zebra ZT231 / ZT231 RFID", "brand": "Zebra",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Mid-range Industrial", "RFID Optional", "203/300 dpi"],
     "short_desc": "Mid-range industrial with optional RFID encoding — perfect for retail item-level rollouts.",
     "long_desc": "The ZT231 builds on the ZT211 platform with optional UHF RFID encoding. Same rugged industrial chassis, same Zebra Print DNA Suite — now with RFID when you need it.",
     "specs": ["203 / 300 dpi", "12 IPS / 8 IPS",
               "USB + RS-232 + 10/100 Ethernet + USB Host",
               "Optional UHF RFID encoding",
               "Print length 3988 mm (157\")",
               "Print width 104 mm (4.09\")"],
     "use_cases": ["Retail RFID rollouts", "Pharma serialization", "Mid-volume DC"],
     "image_index": 2, "featured": True},
    {"slug": "tsc-ml240p-ml340p", "category": "printer", "name": "TSC ML240P / ML340P", "brand": "TSC",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4.25-inch",
     "tags": ["Mid-range Industrial", "203/300 dpi", "Metal Frame"],
     "short_desc": "Metal-frame mid-range printer family — ML240P (203 dpi) and ML340P (300 dpi).",
     "long_desc": "TSC's mid-range workhorses with all-metal frames, 1000-inch print length capacity and 450 m ribbon. Reliable, repairable, and economical to run.",
     "specs": ["203 / 300 dpi", "6 IPS / 5 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\") at 203 dpi",
               "Print width 108 / 105.7 mm",
               "Ribbon: 450 m"],
     "use_cases": ["Distribution centres", "Manufacturing lines", "3PL"],
     "image_index": 3},
    {"slug": "tsc-mb240t-mb340t", "category": "printer", "name": "TSC MB240T / MB340T", "brand": "TSC",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4.25-inch",
     "tags": ["Mid-range Industrial", "Touch Display", "203/300 dpi"],
     "short_desc": "Mid-range industrial with built-in colour touch display for self-service operation.",
     "long_desc": "The MB240T/MB340T add a colour touchscreen to the proven ML platform — operators load and run jobs without a connected PC. Ideal for shop-floor lines.",
     "specs": ["203 / 300 dpi", "10 IPS / 7 IPS",
               "USB + LAN + RS232 + USB Host",
               "Colour touch LCD",
               "Print length 25,400 mm (1000\") at 203 dpi",
               "Ribbon: 450 m"],
     "use_cases": ["Shop floor lines", "Walk-up kiosks", "Manufacturing WIP"],
     "image_index": 4},
    {"slug": "tsc-t4000", "category": "printer", "name": "TSC T4000 (4-inch)", "brand": "TSC",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Mid-range Industrial", "Value 4-inch"],
     "short_desc": "Compact 4-inch mid-range industrial printer — economical entry to industrial-grade printing.",
     "long_desc": "The T4000 4\" gives you industrial chassis durability in a compact footprint — fits where bigger industrial printers won't, with the same printhead pressure & longevity.",
     "specs": ["203 / 300 dpi", "10 IPS / 7 IPS",
               "USB + RS232 + LAN + USB Host",
               "Print length 1270 mm (50\")",
               "Print width 104 mm (4.09\")",
               "Ribbon: 450 m"],
     "use_cases": ["Compact industrial sites", "Pharma packaging", "Compliance labels"],
     "image_index": 5},
    {"slug": "citizen-cls700", "category": "printer", "name": "Citizen CL-S700", "brand": "Citizen",
     "form": "Mid-range Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Mid-range Industrial", "Citizen"],
     "short_desc": "Citizen's mid-range industrial — proven Japanese build, 10 IPS, full connectivity.",
     "long_desc": "The CL-S700 is Citizen's flagship 4\" mid-range industrial — quiet, repairable, and built to outlast the competition.",
     "specs": ["203 dpi", "10 IPS", "USB + RS232 + IEEE",
               "Print length 812.8 mm (32\")",
               "Print width 104 mm (4\")",
               "Ribbon: 450 m"],
     "use_cases": ["Quiet manufacturing", "Healthcare back-office", "DC operations"],
     "image_index": 0},

    # ── Industrial ──
    {"slug": "zebra-zt411", "category": "printer", "name": "Zebra ZT411", "brand": "Zebra",
     "form": "Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Industrial", "203/300/600 dpi", "Flagship"],
     "short_desc": "Zebra's industrial flagship — choose 203, 300 or 600 dpi for any application.",
     "long_desc": "The ZT411 is the industrial benchmark — colour LCD, 14 IPS at 203 dpi, all-metal die-cast frame, and the 600 dpi variant prints UDI codes and microscopic asset IDs.",
     "specs": ["203 / 300 / 600 dpi", "14 / 10 / 4 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 3988 mm (157\")",
               "Print width 104 mm (4.09\")",
               "Ribbon: 450 m, 1\" core"],
     "use_cases": ["High-volume DC", "Pharma UDI", "Aerospace", "Automotive"],
     "image_index": 1, "featured": True},
    {"slug": "zebra-zt421", "category": "printer", "name": "Zebra ZT421", "brand": "Zebra",
     "form": "Industrial", "dpi": 203, "width": "6.6-inch",
     "tags": ["Industrial", "6-inch wide", "203/300 dpi"],
     "short_desc": "6.6-inch wide-format industrial — drum labels, GHS chemical, hazmat compliance.",
     "long_desc": "The ZT421 prints up to 168 mm (6.6\") wide — built for GHS chemical labels, drum & barrel marking, and hazmat compliance tags that don't fit on a 4-inch printer.",
     "specs": ["203 / 300 dpi", "12 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length 991 mm (39\")",
               "Print width 168 mm (6.6\")",
               "Ribbon: 450 m"],
     "use_cases": ["GHS chemical labels", "Drum & barrel marking", "Hazmat", "Cold-chain"],
     "image_index": 2},
    {"slug": "zebra-zt510", "category": "printer", "name": "Zebra ZT510", "brand": "Zebra",
     "form": "Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Industrial", "Value Industrial", "203/300 dpi"],
     "short_desc": "Value industrial — Zebra's affordable 12 IPS industrial printer for everyday rigor.",
     "long_desc": "The ZT510 hits the value-industrial sweet spot — cast-aluminum frame, 12 IPS at 203 dpi, full Link-OS support, and Bluetooth LE for modern device management.",
     "specs": ["203 / 300 dpi (optional)", "12 IPS",
               "USB + LAN + Serial + Bluetooth LE",
               "Print width 104 mm (4.09\")",
               "Print length up to 3810 mm (150\")",
               "Ribbon: 450 m"],
     "use_cases": ["Value industrial deployments", "Distribution centres", "Compliance"],
     "image_index": 3},
    {"slug": "tsc-mh241t-series", "category": "printer", "name": "TSC MH241T / MH341T / MH641T", "brand": "TSC",
     "form": "Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Industrial", "203/300/600 dpi", "Long Ribbon"],
     "short_desc": "Industrial family with 600 m ribbon capacity — fewer reloads, lower cost per label.",
     "long_desc": "The MH241T (203), MH341T (300) and MH641T (600 dpi) share a single industrial chassis with 600 m ribbon capacity — the longest in their class.",
     "specs": ["203 / 300 / 600 dpi", "14 / 10 / 4 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\") at 203 dpi",
               "Print width 104 mm (4.09\")",
               "Ribbon: 600 m"],
     "use_cases": ["High-volume DC", "Pharma UDI", "Long unattended runs"],
     "image_index": 4},
    {"slug": "tsc-mh261t-mh361t", "category": "printer", "name": "TSC MH261T / MH361T", "brand": "TSC",
     "form": "Industrial", "dpi": 203, "width": "6.61-inch",
     "tags": ["Industrial", "6-inch wide", "203/300 dpi"],
     "short_desc": "6.6-inch wide industrial — drum, GHS, and large-format compliance labels.",
     "long_desc": "TSC's wide-format industrial pair. 12 IPS at 203 dpi over a 168 mm (6.61\") print width — built for big labels at industrial speed.",
     "specs": ["203 / 300 dpi", "12 IPS / 10 IPS",
               "USB + LAN + RS232 + IEEE + USB Host",
               "Print length 14,732 mm (580\")",
               "Print width 168 mm (6.61\")",
               "Ribbon: 450 m"],
     "use_cases": ["GHS chemical", "Hazmat compliance", "Drum labels"],
     "image_index": 5},
    {"slug": "tsc-286mt-384mt", "category": "printer", "name": "TSC 286MT / 384MT", "brand": "TSC",
     "form": "Industrial", "dpi": 203, "width": "8.5-inch",
     "tags": ["Industrial", "8-inch wide", "Heavy carton labels"],
     "short_desc": "8.5-inch wide-format industrial — for full-carton labels and pallet tags.",
     "long_desc": "The 286MT (203 dpi) and 384MT (300 dpi) print up to 216 mm (8.5\") wide — built for full-carton labels, pallet tags and large GHS chemical compliance.",
     "specs": ["203 / 300 dpi", "6 IPS / 4 IPS",
               "USB + LAN + RS232 + IEEE + USB Host",
               "Print length 11,430 mm (450\")",
               "Print width 216 mm (8.5\")",
               "Ribbon: 600 m"],
     "use_cases": ["Full-carton labels", "Pallet tags", "Large GHS"],
     "image_index": 0},
    {"slug": "postek-t6000", "category": "printer", "name": "Postek T6000 (4\" / 6\")", "brand": "Postek",
     "form": "Industrial", "dpi": 203, "width": "4 / 6-inch",
     "tags": ["Industrial", "Postek", "4 or 6-inch"],
     "short_desc": "Postek industrial printer — choose 4\" or 6\" width, 14 IPS at 203 dpi.",
     "long_desc": "Postek's T6000 is a value-engineered industrial printer with metal frame and 14 IPS at 203 dpi. Available in 4\" and 6\" widths.",
     "specs": ["203 / 300 dpi (4\" & 6\")",
               "14/12 IPS at 203 dpi, 12/10 IPS at 300 dpi",
               "USB + RS232 + LAN",
               "Print length 2514 mm (99\")",
               "Print width 104 mm (4.1\") or 166 mm (6.55\")",
               "Ribbon: 450 m"],
     "use_cases": ["Value industrial", "Wide-format labels", "Manufacturing lines"],
     "image_index": 1},

    # ── Heavy-Duty Industrial ──
    {"slug": "zebra-zt611", "category": "printer", "name": "Zebra ZT611", "brand": "Zebra",
     "form": "Heavy-duty Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Heavy-duty", "203/300/600 dpi", "Mission-critical"],
     "short_desc": "Heavy-duty 4-inch — 14 IPS, all-metal frame, mission-critical reliability.",
     "long_desc": "The ZT611 is built for sites where downtime is unacceptable. Cast-aluminum frame, 14 IPS at 203 dpi, 600 dpi option for UDI/serialization, Bluetooth 4.0 management.",
     "specs": ["203 / 300 / 600 dpi", "14 / 12 / 6 IPS",
               "USB + LAN + RS232 + Bluetooth 4.0",
               "Print length 3988 mm (157\")",
               "Print width 104 mm (4.09\")",
               "Ribbon: 450 m"],
     "use_cases": ["Mission-critical DC", "24×7 manufacturing", "Pharma UDI"],
     "image_index": 2, "featured": True},
    {"slug": "zebra-zt621", "category": "printer", "name": "Zebra ZT621", "brand": "Zebra",
     "form": "Heavy-duty Industrial", "dpi": 203, "width": "6.6-inch",
     "tags": ["Heavy-duty", "6-inch wide", "Mission-critical"],
     "short_desc": "Heavy-duty 6.6-inch wide-format — for large compliance labels in 24×7 sites.",
     "long_desc": "When you need wide-format labels and zero downtime, the ZT621 delivers — 168 mm print width, 12 IPS, cast-aluminum frame.",
     "specs": ["203 / 300 dpi", "12 IPS / 8 IPS",
               "USB + LAN + RS232 + Bluetooth 4.0",
               "Print length 3810 mm (150\")",
               "Print width 168 mm (6.6\")",
               "Ribbon: 450 m"],
     "use_cases": ["Large GHS compliance", "Hazmat", "Heavy-duty manufacturing"],
     "image_index": 3},
    {"slug": "zebra-220xi4", "category": "printer", "name": "Zebra 220Xi4", "brand": "Zebra",
     "form": "Heavy-duty Industrial", "dpi": 203, "width": "8.5-inch",
     "tags": ["Heavy-duty", "8.5-inch wide", "Workhorse"],
     "short_desc": "Heavy-duty 8.5-inch — full-carton labels in the toughest environments.",
     "long_desc": "The Xi4 platform is Zebra's no-compromise workhorse. 216 mm print width, all-metal die-cast frame, 24×7 ready. When you need a printer that simply won't stop, this is it.",
     "specs": ["203 / 300 dpi", "10 IPS / 6 IPS",
               "USB + RS232 + Parallel",
               "Print width 216 mm (8.5\")",
               "Direct-thermal or thermal-transfer",
               "Ribbon: 450 m"],
     "use_cases": ["Full-carton labels", "Pallet tags", "Hazmat compliance"],
     "image_index": 4},
    {"slug": "tsc-mx241p-series", "category": "printer", "name": "TSC MX241P / MX341P / MX641P", "brand": "TSC",
     "form": "Heavy-duty Industrial", "dpi": 203, "width": "4-inch",
     "tags": ["Heavy-duty", "203/300/600 dpi", "18 IPS"],
     "short_desc": "Heavy-duty 4-inch — 18 IPS at 203 dpi, the fastest in its class.",
     "long_desc": "The MX241P series tops the speed charts — 18 IPS at 203 dpi means more labels per shift. Cast frame, 600 m ribbon, 600 dpi option for UDI.",
     "specs": ["203 / 300 / 600 dpi", "18 / 14 / 6 IPS",
               "USB + LAN + RS232 + USB Host",
               "Print length up to 25,400 mm (1000\") at 203 dpi",
               "Print width 104 mm (4.09\")",
               "Ribbon: 600 m"],
     "use_cases": ["High-throughput DC", "Pharma UDI", "Manufacturing lines"],
     "image_index": 5, "featured": True},
    {"slug": "postek-t8000", "category": "printer", "name": "Postek T8000 (4\" / 6\" / 8\")", "brand": "Postek",
     "form": "Heavy-duty Industrial", "dpi": 203, "width": "4 / 6 / 8-inch",
     "tags": ["Heavy-duty", "Postek", "4 / 6 / 8-inch"],
     "short_desc": "Postek heavy-duty industrial — choose 4\", 6\" or 8\" width.",
     "long_desc": "The Postek T8000 covers the full width spectrum at heavy-duty industrial speeds. 14 IPS at 203 dpi in 4\", scaling to 8.5\" wide-format for full carton labels.",
     "specs": ["203 / 300 dpi", "14 / 12 / 10 IPS at 203",
               "USB + RS232 + LAN",
               "Print length 2514 mm (99\")",
               "Print width 4.1\" / 6.6\" / 8.5\"",
               "Ribbon: 625 m"],
     "use_cases": ["Heavy-duty DC", "Full-carton labels", "Hazmat"],
     "image_index": 0},
]
