"""Seed data for the DRISHTI product catalog.
Images are curated Unsplash/Pexels URLs appropriate to each product category.
"""

# Category-appropriate image pools (rotated per SKU)
PRINTER_IMAGES = [
    "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1645303509515-d6d1e85a6b41?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1612815292258-f4354f07f358?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1613423885632-4a065c1ae55d?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1586528116493-a029325540fa?auto=format&fit=crop&w=1200&q=80",
]
LABEL_IMAGES = [
    "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1580901368919-7738efb0f87e?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1624365169364-0640dd10e180?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1567958451986-2de427a4a0be?auto=format&fit=crop&w=1200&q=80",
]
RIBBON_IMAGES = [
    "https://images.unsplash.com/photo-1609607569087-14a50d6c1bef?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1597589827703-f84d0f6e389a?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1580479389094-9a4e9ab80be1?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
]


def _img(category: str, index: int) -> str:
    pool = {"printer": PRINTER_IMAGES, "label": LABEL_IMAGES, "ribbon": RIBBON_IMAGES}[category]
    return pool[index % len(pool)]


SEED_PRODUCTS = [
    # Printers
    {"slug": "zebra-zd230", "category": "printer", "name": "Zebra ZD230", "brand": "Zebra", "form": "Desktop",
     "dpi": 203, "width": "4-inch", "tags": ["Entry-level", "Desktop", "Direct Thermal", "Thermal Transfer"],
     "short_desc": "Reliable 4-inch desktop thermal printer for low-to-mid volume labeling — retail, shipping, inventory.",
     "long_desc": "The Zebra ZD230 delivers dependable performance for businesses transitioning from legacy desktop printers. Built on proven Zebra engineering, it handles 1D & 2D barcodes, shipping labels and basic asset tagging with ease. The dual-motor gear train keeps throughput consistent even as demand spikes, and the dual-wall frame absorbs the knocks of real-world counter and warehouse environments.",
     "specs": ["203 dpi native resolution", "4.09\" max print width", "152 mm/s (6 ips) max print speed",
               "USB + Ethernet connectivity", "74 MB Flash / 256 MB RAM", "ZPL + EPL compatible",
               "Media roll OD 5\", core 0.5\" / 1\"", "Operating temp 5–40°C"],
     "use_cases": ["Small retail POS & price labels", "E-commerce shipping labels",
                   "Light warehousing inventory", "Clinic patient labels"],
     "image_index": 0, "featured": True},
    {"slug": "zebra-zd621", "category": "printer", "name": "Zebra ZD621", "brand": "Zebra", "form": "Desktop",
     "dpi": 300, "width": "4-inch", "tags": ["Premium Desktop", "300 dpi", "Healthcare-ready", "Wi-Fi"],
     "short_desc": "Premium 4-inch desktop with LCD, peeler, and healthcare-disinfectant-ready housing.",
     "long_desc": "The Zebra ZD621 is Zebra's flagship desktop printer — a 300 dpi workhorse with a colour LCD, modular connectivity (USB/LAN/BT/Wi-Fi) and Link-OS manageability. The healthcare variant uses disinfectant-ready plastics to survive daily cleaning in clinical environments, while the peeler and cutter options make it equally at home in e-commerce pick & pack.",
     "specs": ["203 or 300 dpi variants", "4.09\" print width", "203 mm/s (8 ips)",
               "USB / LAN / Bluetooth / Wi-Fi", "256 MB Flash / 512 MB RAM", "Link-OS + ZPL + EPL",
               "Optional peeler / cutter", "Disinfectant-ready housing (healthcare SKU)"],
     "use_cases": ["Hospital wristbands & medication", "High-res carton labels", "Pick-and-pack e-commerce",
                   "Jewelry & asset tags"],
     "image_index": 1, "featured": True},
    {"slug": "tsc-te244", "category": "printer", "name": "TSC TE244", "brand": "TSC", "form": "Desktop",
     "dpi": 203, "width": "4-inch", "tags": ["Value", "Desktop", "Retail"],
     "short_desc": "Value-priced 4-inch TT desktop printer — great starter for retail and small logistics.",
     "long_desc": "The TSC TE244 hits the sweet spot between price and performance. Robust clamshell design, industry-standard connectivity and TSPL compatibility mean it drops into existing workflows with no surprises.",
     "specs": ["203 dpi", "4.25\" max print width", "152 mm/s speed", "USB + Serial + LAN",
               "8 MB Flash / 64 MB RAM", "TSPL-EZ + EPL2 + ZPL emulations"],
     "use_cases": ["Apparel tags", "Shipping labels", "Inventory", "Small-format asset tags"],
     "image_index": 2},
    {"slug": "tsc-mh240p", "category": "printer", "name": "TSC MH240P", "brand": "TSC", "form": "Industrial",
     "dpi": 203, "width": "4-inch", "tags": ["Industrial", "High Volume", "24×7", "Touch LCD"],
     "short_desc": "Industrial 4-inch built for 24×7 warehouse & manufacturing lines. Metal housing, touch LCD.",
     "long_desc": "The MH240P combines industrial durability (all-metal casting) with modern usability (5\" touch LCD, front-mounted USB). The 600 m ribbon capacity and 300 mm/s speed keep high-throughput DC operations moving without constant media reloads.",
     "specs": ["203 dpi (300/600 dpi options)", "4.33\" print width", "356 mm/s max speed",
               "USB / LAN / Serial / USB host", "128 MB Flash / 128 MB RAM", "600 m ribbon capacity",
               "5\" colour touch LCD", "Optional cutter / peeler / rewinder"],
     "use_cases": ["Warehouse & logistics hub", "Manufacturing WIP", "Pharma serialization", "Cold storage"],
     "image_index": 3, "featured": True},
    {"slug": "honeywell-pc42", "category": "printer", "name": "Honeywell PC42", "brand": "Honeywell",
     "form": "Desktop", "dpi": 203, "width": "4-inch",
     "tags": ["Desktop", "Plug & Play", "Value", "Compact"],
     "short_desc": "Compact, easy-to-load 4-inch desktop — ideal for office, clinic, retail counter.",
     "long_desc": "The PC42 is the definition of \"just works\". Clamshell design loads media in seconds, a tiny desktop footprint fits anywhere, and Honeywell-grade reliability means it keeps running long past its warranty.",
     "specs": ["203 dpi", "4.25\" print width", "101 mm/s speed", "USB + LAN",
               "4 MB Flash / 8 MB RAM", "Honeywell Direct Protocol + ZPL + EPL"],
     "use_cases": ["Office document labels", "Clinic patient labels", "Small retail POS", "Event badges"],
     "image_index": 4},
    {"slug": "sato-cl4nx-plus", "category": "printer", "name": "SATO CL4NX Plus", "brand": "SATO",
     "form": "Industrial", "dpi": 305, "width": "4-inch",
     "tags": ["Industrial", "Mission-critical", "Multi-language", "Self-diagnostic"],
     "short_desc": "Mission-critical industrial printer with colour LCD, self-diagnostic engine, universal ribbon support.",
     "long_desc": "The CL4NX Plus is an operator-free workhorse — the printer diagnoses itself, prompts for correct ribbon/media, supports every major protocol and prints in 47 languages. When downtime costs real money, this is the printer.",
     "specs": ["305 dpi (203 / 609 dpi options)", "4.1\" print width", "356 mm/s speed",
               "USB / LAN / BT / Wi-Fi / RFID option", "512 MB Flash / 512 MB RAM",
               "SBPL + SZPL + SDPL + STCL + SEPL", "Self-diagnostic engine", "IoT-ready"],
     "use_cases": ["Automotive assembly", "Electronics manufacturing", "Cold-chain pharma", "Aerospace traceability"],
     "image_index": 5, "featured": True},

    # Labels
    {"slug": "label-paper-tt", "category": "label", "name": "Thermal Transfer Paper Labels",
     "brand": "DRISHTI Stock", "form": "Face-stock: Paper",
     "tags": ["Thermal Transfer", "Paper", "Economical", "Shipping"],
     "short_desc": "Semi-gloss or matte paper labels for TT printing — shipping, inventory, price marking.",
     "long_desc": "DRISHTI's most-shipped SKU. Economical, reliable TT-coated paper with strong permanent adhesive. Custom die-cut to your exact size and perf — one working day for common sizes, three for fully bespoke specs.",
     "specs": ["Face-stock: 80 gsm semi-gloss or matte TT paper", "Adhesive: Permanent hot-melt (HM4000)",
               "Liner: 55 gsm white glassine", "Standard sizes 25×15 to 150×100 mm (custom available)",
               "Roll OD up to 220 mm / core 40 mm or 76 mm", "Pairs with wax or wax-resin ribbon"],
     "use_cases": ["E-commerce shipping", "Warehouse inventory", "Price & product labels", "Carton labels"],
     "image_index": 0, "featured": True},
    {"slug": "label-dt", "category": "label", "name": "Direct Thermal Labels", "brand": "DRISHTI Stock",
     "form": "Face-stock: Thermal Paper",
     "tags": ["Direct Thermal", "No Ribbon", "Logistics", "POS"],
     "short_desc": "Top-coated direct thermal labels — print without ribbon. Perfect for shipping and POS.",
     "long_desc": "Top-coated direct thermal face-stock prints crisply without a ribbon — lowest total cost for short-life labels. Ideal for shipping dockets, parcel lockers, airline baggage and POS receipts with 3–6 month usable life.",
     "specs": ["Face-stock: 76 gsm top-coated DT paper", "Shelf life: 6 months (normal conditions)",
               "Adhesive: Permanent acrylic", "Sizes: 50×25 to 100×150 mm",
               "Roll OD up to 220 mm"],
     "use_cases": ["Parcel & last-mile labels", "POS receipts", "Airline baggage tags", "Visitor badges"],
     "image_index": 1},
    {"slug": "label-polyester-silver", "category": "label",
     "name": "Polyester Silver Asset Labels", "brand": "DRISHTI Stock",
     "form": "Face-stock: Polyester",
     "tags": ["Polyester", "Asset Tracking", "Durable", "Chemical-resistant"],
     "short_desc": "High-durability matt silver polyester for asset tags — chemical, abrasion, temperature resistant.",
     "long_desc": "When an asset tag has to survive the life of the asset, use polyester. DRISHTI's matt silver PET face-stock is rated for -40 to +150°C, resists most industrial chemicals and solvents, and pairs with full-resin ribbon for 7+ year outdoor durability.",
     "specs": ["Face-stock: 50 μm matt silver polyester", "Operating temp: -40 to +150°C",
               "Adhesive: High-tack acrylic (P30) or silicone (-40°C)",
               "Requires full-resin TT ribbon", "Outdoor life 7+ years"],
     "use_cases": ["IT asset tags", "Capital equipment", "Utility meters", "Outdoor signage"],
     "image_index": 2, "featured": True},
    {"slug": "label-void", "category": "label", "name": "Void / Tamper-Evident Labels",
     "brand": "DRISHTI Stock", "form": "Face-stock: Polyester Void",
     "tags": ["Void", "Tamper-evident", "Security", "Anti-counterfeit"],
     "short_desc": "Polyester labels that leave a VOID pattern on removal — seals, warranty, regulatory evidence.",
     "long_desc": "Partial-transfer or full-transfer VOID polyester. Once peeled, a VOID pattern stays on the substrate — critical for warranty seals, regulatory tamper evidence and anti-counterfeit packaging.",
     "specs": ["Partial-transfer or full-transfer VOID", "Custom VOID pattern & colour options",
               "Requires TT + resin ribbon", "Serialized barcode/QR available"],
     "use_cases": ["Warranty seals", "Regulatory compliance", "Anti-counterfeit packaging", "Evidence bags"],
     "image_index": 3},
    {"slug": "label-jewelry", "category": "label", "name": "Jewelry Dumbbell Tags",
     "brand": "DRISHTI Stock", "form": "Face-stock: Coated Paper / Synthetic",
     "tags": ["Jewelry", "Dumbbell", "Small-format", "Butterfly"],
     "short_desc": "Specialty dumbbell/butterfly tags for jewelry — small print windows, tie-through holes.",
     "long_desc": "Engineered for jewelry retailers — dumbbell and butterfly tags with pre-cut tie-through holes, very small print windows and batch-packed on fan-fold or roll for fast tagging.",
     "specs": ["Window: 56×13 mm typical (custom available)",
               "Coated paper or synthetic (tear-resistant)",
               "TT printable with wax-resin or resin", "Fan-fold or roll packed"],
     "use_cases": ["Jewelry retail", "Watch tagging", "Luxury accessories", "Gem identification"],
     "image_index": 4},

    # Ribbons
    {"slug": "ribbon-wax", "category": "ribbon", "name": "Wax Ribbons", "brand": "DRISHTI Stock",
     "form": "Grade: Wax",
     "tags": ["Wax", "Economical", "Paper Labels", "General Purpose"],
     "short_desc": "Pure wax TT ribbons — most economical grade, ideal for paper labels.",
     "long_desc": "Standard wax formulation for general-purpose paper label printing. Low cost per label, clean print, works across all major TT printers. Not scratch-resistant — choose wax-resin or resin for durability needs.",
     "specs": ["Print speeds up to 300 mm/s", "Compatible with all major TT printers (flat-head)",
               "Widths: 40, 55, 60, 80, 90, 110 mm (custom slit available)",
               "Lengths: 300 m or 450 m", "Cores: 0.5\" or 1\""],
     "use_cases": ["Shipping labels", "Inventory labels", "Price tags", "Carton labels"],
     "image_index": 0, "featured": True},
    {"slug": "ribbon-wax-resin", "category": "ribbon", "name": "Wax-Resin Ribbons",
     "brand": "DRISHTI Stock", "form": "Grade: Wax-Resin",
     "tags": ["Wax-Resin", "Durable", "Paper & Synthetic", "Light Chemical"],
     "short_desc": "Mid-grade ribbons balancing cost and durability — paper and light synthetics.",
     "long_desc": "The best-selling ribbon grade in logistics. Wax-resin prints cleanly on both paper and light synthetic labels, offers smudge and scratch resistance, and handles mild chemical exposure.",
     "specs": ["Smudge & scratch-resistant", "Mild chemical & solvent resistance",
               "Print speeds up to 250 mm/s", "Widths: 40–110 mm (custom slit)",
               "Lengths: 300 m or 450 m"],
     "use_cases": ["Logistics & 3PL", "Pharma outer carton", "Mid-life asset tags", "Cold-chain"],
     "image_index": 1, "featured": True},
    {"slug": "ribbon-resin", "category": "ribbon", "name": "Full Resin Ribbons",
     "brand": "DRISHTI Stock", "form": "Grade: Full Resin",
     "tags": ["Full Resin", "Chemical-resistant", "Synthetic", "Industrial"],
     "short_desc": "Premium full-resin ribbons for polyester, polypropylene and extreme environments.",
     "long_desc": "Full resin is the industrial gold standard — chemical, solvent and alcohol resistant, survives autoclave sterilisation and outlasts the asset it's printed on. Essential for polyester asset tags and regulated manufacturing.",
     "specs": ["Chemical, solvent & alcohol resistant", "Survives autoclave & hot-wash cycles",
               "Temp resistance: up to 250°C", "Widths: 40–110 mm", "Lengths: 300 m",
               "Pairs with polyester or polypropylene face-stock"],
     "use_cases": ["IT asset tags", "Automotive under-hood", "Pharma autoclave", "Oil & gas"],
     "image_index": 2, "featured": True},
    {"slug": "ribbon-near-edge", "category": "ribbon", "name": "Near-Edge Ribbons",
     "brand": "DRISHTI Stock", "form": "Head: Near-Edge",
     "tags": ["Near-Edge", "High-speed", "Packaging", "Industrial"],
     "short_desc": "Near-edge ribbons for high-speed packaging printers (Videojet, Domino, SATO TG).",
     "long_desc": "Specially formulated for near-edge print-heads on high-speed continuous packaging lines. Back-coated to protect the head and deliver consistent quality at 600 mm/s.",
     "specs": ["Print speeds up to 600 mm/s", "Back-coated for head protection",
               "Compatible with Videojet, Domino, SATO TG, Markem-Imaje",
               "Widths: 33–60 mm", "Lengths: 900 m – 1200 m"],
     "use_cases": ["FMCG packaging lines", "Food MRP coding", "Batch & expiry codes", "Flexible pouches"],
     "image_index": 3},
    {"slug": "ribbon-custom", "category": "ribbon", "name": "Custom-Width Ribbons",
     "brand": "DRISHTI Stock", "form": "Slitting: Custom",
     "tags": ["Custom Width", "Slitting", "Bulk"],
     "short_desc": "Slitting service for any master roll — exact widths matched to your label spec.",
     "long_desc": "In-house slitting lets you match ribbon width exactly to your label — minimising waste, maximising usable meterage. MOQ applies. Turnaround 3–5 working days for standard grades.",
     "specs": ["Minimum width: 24 mm", "Any length up to 600 m",
               "All grades: wax, wax-resin, full resin, near-edge",
               "MOQ: 20 rolls per spec"],
     "use_cases": ["Custom label formats", "OEM partner supply", "Bulk procurement"],
     "image_index": 4},
]


def product_image(p: dict) -> str:
    if p.get("image_url"):
        return p["image_url"]
    return _img(p["category"], p.get("image_index", 0))
